debug: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webflash?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: webflash
    password: webflash190602@ABC
  jpa:
    hibernate:
      ddl-auto: create
  activiti:
    check-process-definitions: true
    database-schema-update: update
    history-level: full
    db-history-used: true
    process-definition-location-prefix: classpath:/bpmn/
